<?php
/**
 * XRPLWinAnalyzer (XWA) main config file.
 */

$r = [

  # Sync this version with composer.json
  'version' => '0.0.1',

  /*
  |--------------------------------------------------------------------------
  | Search limit per page
  |--------------------------------------------------------------------------
  | Default: 1000
  | How much results to pull before paginating.
  */
  'limit_per_page' => env('XWA_SEARCH_LIMIT', 1000), //1000

  /*
  |--------------------------------------------------------------------------
  | Paginator breakpoint
  |--------------------------------------------------------------------------
  | Default: 500
  | How much results one request can pull per txType, before paginating multiple ledger days.
  | This value does not take into account internal per-ledger-day paginating.
  | Max transactions returned per request can be eg. <paginator_breakpoint>*<number of transaction types>
  | for internal (ledger-day) paginating - in short when there is large amount of transactions in one day.
  | Warning: Changing this value requires clearing reverse proxy cache (eg. Varnish, CloudFront ...)
  |   It is recommended not to change this value on production that is already running.
  */
  //'paginator_breakpoint' => env('XWA_PAGINATIOR_BREAKPOINT', 500),

  /*
  |--------------------------------------------------------------------------
  | Transaction types list
  |--------------------------------------------------------------------------
  | Autogenerated from codebase
  | List of transaction types, keyed by type integer.
  */
  'transaction_types' => [
    //<DTransaction::TYPE> => Typenamepart,
    //1 => 'Payment',
    //2 => 'Activation',
    //...
  ],
  
  /*
  |--------------------------------------------------------------------------
  | XRPL Address characters
  |--------------------------------------------------------------------------
  | Characters that can be in address.
  | DynamoDB transaction databases are created according to thiese characters.
  */
  'address_characters' => [
    //letters lowercase:
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
    //numbers:
    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
  ],

  'queue_groups' => [
    'q1' => ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
    'q2' => ['m', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x'],
    'q3' => ['y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
  ],

  'queue_groups_reversed' => [
    //Autogenerated
  ],
];

//generate transaction_types
$dir = __DIR__.'/../app/Models';
$dirlist = \scandir($dir);
foreach($dirlist as $v) {
  if(\str_starts_with($v,'DTransaction') && $v !== 'DTransaction.php' && \str_ends_with($v,'.php')) {
    $modelname = '\\App\\Models\\'.\substr($v,0,-4);
    $r['transaction_types'][$modelname::TYPE] = \substr(\substr($v,0,-4),12);
  }
}

\ksort($r['transaction_types'],SORT_NUMERIC);


//generate queue_groups_reversed
foreach($r['queue_groups'] as $name => $v_chars) {
  foreach($v_chars as $v_char) {
    $r['queue_groups_reversed'][$v_char] = $name;
  }
}

return $r;
